# 【ServerlessFrameworkでS3静的ホスティングを設定する】
# ServerlessFrameworkにはファイルをS3にアップロードする機能が標準で備わっていない
# したがって、pluginを使用する
# （グローバルインストールでよい）
# npm install -g serverless-s3-sync
# serverless plugin install --name serverless-s3-sync

service: serverless-s3-deploy-sample
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-1

  # you can add statements to the Lambda function's IAM Role here
  # LambdaにCloudFrontの権限を与える
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cloudfront:ListDistributions"
            - "cloudfront:CreateInvalidation"
          Resource: arn:aws:cloudfront::067625212445:distribution/E1YCQXARB1OVWZ

plugins:
  - serverless-s3-sync

custom:
  # webSiteName: s3-static-site-hosting.com
  s3Sync:
    # 静的アセットをアップロードするバケットの指定
    # アップロードするローカルのディレクトリを指定
    - bucketName: hogehogehoges3bucket2023
      localDir: static

functions:
  clearCache:
    handler: handler.lambdaHandler
    events:
      - s3:
          bucket: hogehogehoges3bucket2023
          event: "s3:ObjectCreated:*"
          # ↓こちらの指定は正しくない
          # event: "s3:*"

          # rulesは特定のファイル名のオブジェクトのときだけLambdaを起動できる
          # Lambdaで判定しても良いのだが、あちらは起動回数に応じて料金がかかるので
          # prefixはファイル名の一部
          # suffixは拡張子を指定できる
          # rules:
          #   - prefix: images/
          #   - suffix: .html

          # すでに存在するバケットを対象にする場合は指定する
          # （デフォルトではバケットが新しく作成されてしまう？）
          existing: true

# 【s3で使用できるイベント例】
# s3:ObjectCreated:* オブジェクト作成
# s3:ObjectRemoved:* オブジェクト削除
# s3:ObjectRestore:* Glacierから復元（開始、完了）
# s3:LifecycleExpiration:* ライフサイクル設定でオブジェクトを削除
# s3:ObjectTagging:* オブジェクトにタグ追加・削除
# s3:ObjectACL:PUT オブジェクトのACL設定が変更

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hogehogehoges3bucket2023

        # パブリックアクセスでバケットを作成する場合
        # AccessControl: PublicRead

        # パブリックアクセスをすべてブロックにする
        AccessControl: Private

        # ブロックパブリックアクセスを個別に設定する場合
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

        # バージョニングの有効化
        VersioningConfiguration:
          Status: Enabled

        # バケットの暗号化を設定
        # 暗号化キーをAmazon S3 マネージドキー(SSE-S3)に設定
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

        # 静的ホスティングした際のドキュメントルート
        WebsiteConfiguration:
          IndexDocument: index.html
          # ErrorDocument: error.html

    # バケットポリシーの記述
    # 静的ホスティングできるようになる
    StaticSiteHostingS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          # 定義済みのバケットを参照する
          Ref: MyS3Bucket
        PolicyDocument:
          # バケットポリシーのバージョンの指定は固定
          Version: '2012-10-17'
          Statement:
            # Sidは任意で割り当てることができるが、ポリシー内で重複してはいけない
            - Sid: PublicReadGetPutObject
              Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
                # - "s3:PutObject"
              Resource: arn:aws:s3:::hogehogehoges3bucket2023/*

# S3でwebサイトを静的ホスティングするには？
# 最低限の設定だと、以下のようにする
# ・バケットのアクセス許可設定をパブリックアクセスにする
# ・バケットポリシーを追記する
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Sid": "myBucketPolicyStatementId",
#             "Effect": "Allow",
#             "Principal": {
#                 "AWS": "*"
#             },
#             "Action": "s3:*",
#             "Resource": "arn:aws:s3:::hogehogehoges3bucket2023/*"
#         }
#     ]
# }
# 権限には以下のようなものもある
# "s3:GetObject"
# "s3:PutObject"
# "s3:DeleteObject"
# その他の設定（マネジメントコンソール）
# ・バケットのバージョニングを有効にする
# ・デフォルトの暗号化→サーバー側の暗号化を有効にする
# ・暗号化キータイプをAmazon S3キー(SSE-S3)にする
# 【注意】
# ・静的ウェブサイトホスティングの有効化と、
#   アクセス許可設定でパブリックアクセスの許可だけでは、
#   エンドポイントにアクセスできない(403 Forbiddenとなる)
# ・上記に加えてバケットポリシーに適切な記述をすることでS3のURLにアクセスできるようになる
# ・S3のバケットポリシーはデフォルトで全拒否になっている
# ・バケットのバージョニングを有効にしていると、バケットを削除することができなくなる
#   CloudFormationスタックも削除できなくなる
# 【問題】
# 初めにパブリックアクセスのみだとindex.htmlを開くことはできたが、cssの読み込みがされていなかった
# 静的ウェブサイトホスティング用のバケットウェブサイトエンドポイントへのアクセスは403エラーで権限がないのでアクセスできなかった
# だが、バケットポリシーを追記したらindex.html単体を開いてスタイルが適用されていることが確認できた
# もちろん静的ホスティングのエンドポイントにもアクセスできた
# そこまではいいのだが、バケットポリシーを削除したら今度はindex.htmlのスタイルが適用されていた
# 静的ホスティングのエンドポイントはちゃんとアクセスできないようになっていた
# 最初にindex.htmlのスタイルが適用されなかった原因がよくわからない
# 【解決】
# バケットポリシーを削除してから反映が遅れていただけだった
# やはりパブリックアクセスの許可だけだと基本的にリソース（style.css）の取得ができない
# index.htmlやstyle.cssを開いてオブジェクトURLにアクセスしても
# "This XML file does not appear to have any style information associated with it. The document tree is shown below."
# と表示されアクセスできないようになっている
# また、index.htmlなどのリソースをコンソール画面から開くを押して閲覧できるが、
# あれは一時的に発行されるURLですぐに閲覧できなくなる
